sf_vlc_job:
    pattern:  /job/{url}/
    defaults: { _controller: SfVlcJobsBundle:Jobs:job }

sf_vlc_jobs_list:
    pattern:  /
    defaults: { _controller: SfVlcJobsBundle:Jobs:jobs }

sf_vlc_jobs_list_by_tag:
    pattern:  /{tag}/
    defaults: { _controller: SfVlcJobsBundle:Jobs:jobs }