parameters:
#    sf_vlc_jobs.example.class: SfVlc\JobsBundle\Example

services:
#    sf_vlc_jobs.example:
#        class: %sf_vlc_jobs.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
